### ISSUE TITLE
PHP Composer Update  "The .git directory is missing "

### ISSUE THREAD

**Issue by wanaoishi** [CoreSphere/ConsoleBundle#27]
During update I have the following error: 

php composer.phar update  
Loading composer repositories with package information
Updating dependencies (including require-dev)
- Updating coresphere/console-bundle dev-master (ac950e6 => 6cf6090)
  
  [RuntimeException]  
  The .git directory is missing from /vendor/coresphere/console-bundle/CoreSphere/ConsoleBundle, see http://getcomposer.org/commit-deps for more information  

Any idea why?

**Comment by salarmehr** [comment]
@wanaoishi That is a workaround. 
I had the issue several times. If deleting a folder is safe composer need to do it by itself.
