### ISSUE TITLE
Autocomplete: Parameters

### ISSUE THREAD

**Issue by Kevinrob** [CoreSphere/ConsoleBundle#31]
It would be better if the interface would complete the parameters of the method too.  

PS: thanks for the current version!

**Comment by TomasVotruba** [comment]
I guess can be closed, duplicate to #9

**Comment by Kevinrob** [comment]
This is not the same thing. #9 is about the name of the command.

**Comment by TomasVotruba** [comment]
It uses similar logic. Fetching data and providing them to output.

Anayway, can you prepare PR?

**Comment by Kevinrob** [comment]
For now I don't have time. But I will try when I have some times.

**Comment by TomasVotruba** [comment]
@Kevinrob That would be great!
