### ISSUE TITLE
[error] Not Found for every command

### ISSUE THREAD

**Issue by picks44** [CoreSphere/ConsoleBundle#32]
Hi,

For one of my project, I get a "[error] Not Found" error every time I try to fire a command...
On other projetcs, the bundle works fine... I've check configuration, uninstalled/reinstalled the bundle...
Any clue ?
This happens both in local dev mode or on preprod server.

**Comment by picks44** [comment]
up ?

**Comment by laszlokorte** [comment]
I have no idea what it could be. Could you look into your logs and try to get a more precise error message?

**Comment by picks44** [comment]
Main error seems to be : 
[2015-05-18 12:34:23] emergency.EMERGENCY: Maximum execution time of 30 seconds exceeded {"type":1,"file":"C:\\wamp\\www\\DESiwid\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Process\\ProcessPipes.php","line":287} []
But it's never on the same route... Very strange.

**Comment by laszlokorte** [comment]
What command are you trying to execute?

**Comment by picks44** [comment]
a simple cache:clear. but I also tried others like assets:dump, same error...

**Comment by laszlokorte** [comment]
do you use the same symfony version for this project and the projects for which it is working?

**Comment by picks44** [comment]
Yep, 2.3...

**Comment by picks44** [comment]
OK, I found the solution, but still, my other working project was not configured this way...
I only had to declare the ConsoleBundle in routing_dev.yml BEFORE my AppBundle...
And now it's working.
Thks for your time !
