### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by TomasVotruba** [CoreSphere/ConsoleBundle#40]
Last version was tagged 2 years ago, what about tagging new one?

**Comment by laszlokorte** [comment]
:+1:

I am currently not working with symfony myself hence this bundle is not getting all the attention it deserves. I have published a new tag.

**Comment by TomasVotruba** [comment]
Great, thank you! You're so fast.

I'm about to use this, so I might send few more PRs.

One more important think that is not possible to do via PR. To active Travis (CI tests), you need to go to https://travis-ci.org/ and add this package manually. After that, we'll see if tests are passing or not (I'll send PR adding a nice badge that will tell us as wellú.
