### ISSUE TITLE
PHP 5.4

### ISSUE THREAD

**Issue by picks44** [CoreSphere/ConsoleBundle#47]
Why did you remove PHP versions 5.3 and 5.4 ? I can't use the updated version of the bundle now, and SF2.7 allows using >=5.3.9...

**Comment by TomasVotruba** [comment]
First, you should always use tagged version if possible.
0.2 does support it and there are no new features yet.

How does your `composer.json` look like?


As for PHP version, check out http://php.net/supported-versions.php. PHP 5.4 security support end in few days, meaning will be dangerous to use it in production. Thus settings PHP 5.5 as min.

**Comment by picks44** [comment]
When I updated my vendors I got this error : "coresphere/console-bundle dev-master requires php >=5.5 -> your PHP version (5.4.41-0+deb7u1) or "config.platform.php" value does not satisfy that requirement."

I used "coresphere/console-bundle": "dev-master", but I rolled back to "coresphere/console-bundle": "0.1.*".

My production server will be upgraded to 5.5 this fall, but in the meantime I'm stuck with 5.4.

**Comment by TomasVotruba** [comment]
In your `composer.json`, you can use:

```php
"coresphere/console-bundle": "~0.1"
```

This will make sure you'll get all possible compatible versions.

Using `dev-master` makes sense only when there is no stable tag.

**Comment by picks44** [comment]
OK thks.

**Comment by TomasVotruba** [comment]
@picks44 Dlag do help!
