### ISSUE TITLE
Catchable Fatal Error

### ISSUE THREAD

**Issue by skududufru** [CoreSphere/ConsoleBundle#53]
Hello,

Got an error message : 
> Catchable Fatal Error: Argument 3 passed to CoreSphere\ConsoleBundle\Controller\ConsoleController::__construct() must be an instance of Symfony\Bundle\FrameworkBundle\Console\Application, string given, called in [myPath]\app\cache\dev\appDevDebugProjectContainer.php on line 462 and defined" at [myPath]\vendor\coresphere\console-bundle\Controller\ConsoleController.php line 45

**Comment by olix21** [comment]
Not the same, but close for me:

Catchable Fatal Error: Argument 3 passed to CoreSphere\ConsoleBundle\Controller\ConsoleController::__construct() must be an instance of Symfony\Bundle\FrameworkBundle\Console\Application, string given, called in [my_path]/app/cache/dev/appDevDebugProjectContainer.php on line 638 and defined

**Comment by TomasVotruba** [comment]
Could you find what string it is?
Also, what version do you use?

**Comment by skududufru** [comment]
The string is "dev" : 
<code>
protected function getCoresphereConsole_ControllerService()
    {
        return $this->services['coresphere_console.controller'] = new \CoreSphere\ConsoleBundle\Controller\ConsoleController($this->get('templating'), $this->get('coresphere_console.executer'), 'dev');
    }</code>

Version : "dev-master". Can't found the version number

**Comment by TomasVotruba** [comment]
Thank you. I've prepared fixing PR.

Also I recommend you using stable version to prevent such issues. Any commit can break the master, so it's not very safe to use it like this.

**Comment by skududufru** [comment]
Thank you too. I take note about the <code>dev-master</code> tag.

**Comment by TomasVotruba** [comment]
@skududufru @olix21 It's merged, could you test `composer update` and confirm it's ok now?
