### ISSUE TITLE
Invalid Argument Exception

### ISSUE THREAD

**Issue by Guilain** [CoreSphere/ConsoleBundle#55]
Hi
Since the last update, i have this error when i don't add argument or when i add two arguments ...

[InvalidArgumentException]                                                                     
  The file "/xx/xx/xx/www/app/config/config_Array.yml" does not exist.

**Comment by laszlokorte** [comment]
@TomasVotruba any idea? I will take a look at it my self later but maybe you know it out of your head.

**Comment by TomasVotruba** [comment]
@Guilain Hi, could you describe more details?

**Comment by Guilain** [comment]
@TomasVotruba Hi :)
There is no entry in logs ... 
(The last command in dev env is "cache:clear --env=dev --no-debug")
```
CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Warning: Missing argument 2 for Symfony\Component\HttpKernel\Kernel::__construct()" at /home/sylappsejz/sylapps/www/app/bootstrap.php.cache line 2374 
Context: {"exception":"Object(Symfony\\Component\\Debug\\Exception\\ContextErrorException)"} 
```
![console](https://cloud.githubusercontent.com/assets/4057005/9785777/043cf2ce-57b5-11e5-81a3-a23dbbf44263.jpg)

**Comment by TomasVotruba** [comment]
@Guilain Thanks for more details. Before I check it, what version do you use? Last stable?

**Comment by Guilain** [comment]
@TomasVotruba i use this version : coresphere/console-bundle 0.3.0

**Comment by laszlokorte** [comment]
Any progress here? have you tried using the the 0.2.0 version instead?

**Comment by arvind-d** [comment]
I have the same problem here, whenever I issue a cache:clear --env=prod (when running in dev mode) I get the Internal server error and in log file I have this: "request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Warning: Missing argument 2 for Symfony\Component\HttpKernel\Kernel::__construct()" at /var/www/site/app/bootstrap.php.cache line 2374 {"exception":"[object] (Symfony\\Co"

However, using cache:clear --env=dev works fine.

**Comment by laszlokorte** [comment]
https://github.com/CoreSphere/ConsoleBundle/tree/laszlokorte-patch-1 should fix this error

**Comment by laszlokorte** [comment]
@Guilain @arvind-d should be fixed now in 0.3.1. Does it work for you?

**Comment by arvind-d** [comment]
@laszlokorte, I confirm that 0.3.1 fixed my issue. Thank you for looking into this!

**Comment by laszlokorte** [comment]
@arvind-d Thank you for your feedback.
