### ISSUE TITLE
Just a contribution

### ISSUE THREAD

**Issue by JuanDaniel** [CoreSphere/ConsoleBundle#62]
Hello, really this post isn't to report a bug.
I am so happy for use your web console in my projects.
I review the translations file and i detected that don't are spanish translations.
I created the file translations for spanish.
 I put here.
Greetings...

coresphere_console:
    headline:
        index: "Consola"
    working_directory: 'Directorio de trabajo'
    environment: 'Entorno'
    welcome_message: 'Escriba %command% para obtener una lista de los comandos.'
    loading: 'Cargando...'
    suggestion_head: 'Quieres decir:'
    empty_response: 'Terminado!'

**Comment by laszlokorte** [comment]
Thank you very much. Do you mind creating a pull request?

**Comment by laszlokorte** [comment]
#63
