### ISSUE TITLE
Invalid YAML when installing on Symfony3

### ISSUE THREAD

**Issue by pieside** [CoreSphere/ConsoleBundle#64]
To make this bundle work with Symfony3, I needed to modify the service.yml file. In fact, it was required to single quote all the arguments which starts by @. I don't know why. 

5 - '@templating'
6 - '@coresphere_console.executer'
7 - '@coresphere_console.application'
13 - '@kernel'
18 - '@routing.loader.yml'
35 - '@kernel

**Comment by laszlokorte** [comment]
this was already fixed in #59 and the 0.4.0 release

**Comment by pieside** [comment]
Indeed, I've installed the 0.3.1 version by using `$composer require coresphere/console-bundle`. So, I've updated the `composer.json` file and all is ok now.
Thank you for your fast reply.

**Comment by laszlokorte** [comment]
Oh my bad, I just noticed I did not publish the 0.4.0 tag.
