### ISSUE TITLE
symfony3

### ISSUE THREAD

**Issue by fmronan** [CoreSphere/ConsoleBundle#65]
I have this error with symfony3
Catchable Fatal Error: Argument 1 passed to CoreSphere\ConsoleBundle\Controller\ConsoleController::__construct() must be an instance of Symfony\Component\Templating\EngineInterface, none given, called in /home/genusbzhta/var/cache/dev/classes.php on line 2084 and defined

**Comment by laszlokorte** [comment]
What version of the bundle have you installed?

**Comment by fmronan** [comment]
master, 
not the good version for symfony 3?
"coresphere/console-bundle": "dev-master",

**Comment by laszlokorte** [comment]
Should work. I just cloned symfony-standard (https://github.com/symfony/symfony-standard) and just installed the console bundle and it's working.

Do you have twig installed and configured?

**Comment by fmronan** [comment]
Ok the problem is with my route, thx for your reply

**Comment by laszlokorte** [comment]
So did you get it working?

**Comment by fmronan** [comment]
yes working fine

**Comment by laszlokorte** [comment]
:+1:
