### ISSUE TITLE
cache:clear doesn't work with symfony 3.2

### ISSUE THREAD

**Issue by TanguyGiton** [CoreSphere/ConsoleBundle#73]
The cache:clear command doesn't work anymore from symfony 3.2

**Comment by nexuscreation** [comment]
Have you got the "Warning: str_repeat(): Second argument has to be greater than or equal to 0" error too ?

**Comment by laszlokorte** [comment]
Do you get any error messages?

**Comment by nexuscreation** [comment]
cache:clear -vvv

// Clearing the cache for the dev environment with debug true                                                                        

 // Warming up cache...                                                                                                   

 // Finished                                                                    
                                                                               
  [Symfony\Component\Debug\Exception\ContextErrorException]                    
  Warning: str_repeat(): Second argument has to be greater than or equal to 0  
                                                                               
Exception trace:
 () at /home/servor123/www/symfotest/vendor/symfony/symfony/src/Symfony/Component/Console/Style/SymfonyStyle.php:419
 Symfony\Component\Console\Style\SymfonyStyle->createBlock() at /home/servor123/www/symfotest/vendor/symfony/symfony/src/Symfony/Component/Console/Style/SymfonyStyle.php:72
 Symfony\Component\Console\Style\SymfonyStyle->block() at /home/servor123/www/symfotest/vendor/symfony/symfony/src/Symfony/Component/Console/Style/SymfonyStyle.php:148
 Symfony\Component\Console\Style\SymfonyStyle->success() at /home/servor123/www/symfotest/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:115
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /home/servor123/www/symfotest/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /home/servor123/www/symfotest/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:846
 Symfony\Component\Console\Application->doRunCommand() at /home/servor123/www/symfotest/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
 Symfony\Component\Console\Application->doRun() at /home/servor123/www/symfotest/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/servor123/www/symfotest/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:122
 Symfony\Component\Console\Application->run() at /home/servor123/www/symfotest/vendor/coresphere/console-bundle/Executer/CommandExecuter.php:54
 CoreSphere\ConsoleBundle\Executer\CommandExecuter->execute() at /home/servor123/www/symfotest/vendor/coresphere/console-bundle/Controller/ConsoleController.php:71
 CoreSphere\ConsoleBundle\Controller\ConsoleController->execAction() at n/a:n/a
 call_user_func_array() at /home/servor123/www/symfotest/var/cache/dev/classes.php:4898
 Symfony\Component\HttpKernel\HttpKernel->handleRaw() at /home/servor123/www/symfotest/var/cache/dev/classes.php:4853
 Symfony\Component\HttpKernel\HttpKernel->handle() at /home/servor123/www/symfotest/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:168
 Symfony\Component\HttpKernel\Kernel->handle() at /home/servor123/www/symfotest/web/app_dev.php:27

cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by dancostinel** [comment]
@nexuscreation Same here.

**Comment by iceuponfire** [comment]
i encountered the same issue.

**Comment by laszlokorte** [comment]
This should be fixed in 0.5.0

**Comment by iceuponfire** [comment]
it seems fixed for me. thank you !
