### ISSUE TITLE
[parsererror] SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Tchekda** [CoreSphere/ConsoleBundle#77]
When i try a command,  I always get this error : 
![image](https://user-images.githubusercontent.com/23559888/32865012-9ae93f9a-ca61-11e7-953b-a490f2e5ba6d.png)

**Comment by laszlokorte** [comment]
could you look into the network panel of the browser dev tools and tell what http response you are getting when you enter a command in the console?

**Comment by Tchekda** [comment]
I corrected it, i don't know how but i did
