### ISSUE TITLE
non-existent service "templating" !

### ISSUE THREAD

**Issue by imallinman** [CoreSphere/ConsoleBundle#84]
Hi,

I have this exception in my windows wamp64 server project : 

## The service "coresphere_console.controller" has a dependency on a non-existent service "templating".**

**This is my composer.json**
        "php": ">=5.5.9",
        "coresphere/console-bundle": "dev-master",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/orm": "^2.5",
        "friendsofsymfony/user-bundle": "dev-master",
        "incenteev/composer-parameter-handler": "^2.0",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "^5.0.0",
        "symfony/monolog-bundle": "^3.1.0",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/swiftmailer-bundle": "^2.6.4",
        "symfony/symfony": "3.4.*",
        "symfony/templating": "^3.4",
        "twig/twig": "^1.0||^2.0"

**AppKernet.php :**
        if (in_array($this->getEnvironment(), ['dev', 'test'], true)) {
            $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
            $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
            $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();
            $bundles[] = new CoreSphere\ConsoleBundle\CoreSphereConsoleBundle();
           
 **rooting_dev.yml :**
coresphere_console:
	resource: .
	type: extra

**have run this command :**  
 console assets:install web

**I work with WampServer :** 
Version 3.0.6 - 64bit  
Version Apache : 2.4.23  
Version de PHP : 5.6.25  n
Server Software : Apache/2.4.23 (Win64) PHP/5.6.25 - Port défini pour Apache : 80

Does anybody can help please ?

Thank you,

**Comment by hous04** [comment]
Same problem

**Comment by hous04** [comment]
I have the same problem and solved by adding this in config.yml

> # app/config/config.yml
framework:
    # ...
    templating: { engines: ['twig'] }

**Comment by imallinman** [comment]
Yes, thank you. 

Il works **good** now !
